// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XFCvyN5uFd8iQkAUVavDIRhzQyoocag',
    appId: '1:194381395086:web:3ec67374380143105f05df',
    messagingSenderId: '194381395086',
    projectId: 'nasa-app1',
    authDomain: 'nasa-app1.firebaseapp.com',
    storageBucket: 'nasa-app1.appspot.com',
    measurementId: 'G-7N5XM8M6BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEiFDvymnnrIDMbEJLw0NiCcuhvIILOkE',
    appId: '1:194381395086:android:f677afe154af21875f05df',
    messagingSenderId: '194381395086',
    projectId: 'nasa-app1',
    storageBucket: 'nasa-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQPAnTkqCp2_tncg6JmB5WmrN_bkMi_8',
    appId: '1:194381395086:ios:ca4900d1f4d396795f05df',
    messagingSenderId: '194381395086',
    projectId: 'nasa-app1',
    storageBucket: 'nasa-app1.appspot.com',
    iosClientId: '194381395086-09lndg2i2l2gv3o6ap7bc794vhvscnaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasaApp',
  );
}
